package com.holymanzion.calculator.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme
val PrimaryLight = Color(0xFF6750A4)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFE9DDFF)
val OnPrimaryContainerLight = Color(0xFF22005D)
val SecondaryLight = Color(0xFF625B71)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFE8DEF8)
val OnSecondaryContainerLight = Color(0xFF1E192B)
val TertiaryLight = Color(0xFF9A4523)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFDBCF)
val OnTertiaryContainerLight = Color(0xFF390C00)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val BackgroundLight = Color(0xFFFCF8FF)
val OnBackgroundLight = Color(0xFF1C1B20)
val SurfaceLight = Color(0xFFFCF8FF)
val OnSurfaceLight = Color(0xFF1C1B20)
val SurfaceVariantLight = Color(0xFFE7E0EB)
val OnSurfaceVariantLight = Color(0xFF49454E)
val OutlineLight = Color(0xFF7A757F)
val SurfaceContainerLight = Color(0xFFF1ECF4)
val SurfaceContainerHighLight = Color(0xFFEBE6EE)

// Dark scheme
val PrimaryDark = Color(0xFFCFBCFF)
val OnPrimaryDark = Color(0xFF381E72)
val PrimaryContainerDark = Color(0xFF4F378A)
val OnPrimaryContainerDark = Color(0xFFE9DDFF)
val SecondaryDark = Color(0xFFCBC2DB)
val OnSecondaryDark = Color(0xFF332D41)
val SecondaryContainerDark = Color(0xFF4A4458)
val OnSecondaryContainerDark = Color(0xFFE8DEF8)
val TertiaryDark = Color(0xFFFFB59B)
val OnTertiaryDark = Color(0xFF5D1900)
val TertiaryContainerDark = Color(0xFF7B2F0E)
val OnTertiaryContainerDark = Color(0xFFFFDBCF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val BackgroundDark = Color(0xFF131318)
val OnBackgroundDark = Color(0xFFE6E1E9)
val SurfaceDark = Color(0xFF131318)
val OnSurfaceDark = Color(0xFFE6E1E9)
val SurfaceVariantDark = Color(0xFF49454E)
val OnSurfaceVariantDark = Color(0xFFCAC4CF)
val OutlineDark = Color(0xFF948F99)
val SurfaceContainerDark = Color(0xFF201F25)
val SurfaceContainerHighDark = Color(0xFF2B292F)
